# Server Port
server.port=${PORT:8080}

# Spring Boot Login Info
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

# App Config
spring.application.name=My South Church Backend

# We map the system environment variable to a Spring property
google.credentials.json=${GOOGLE_CREDENTIALS_JSON}

# The email you are impersonating (The Super Admin)
google.admin.email=${GOOGLE_ADMIN_EMAIL}

# Tells Spring Security: "Trust tokens signed by Google/Firebase"
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/my-south-church