# Server Port
server.port=${PORT:8080}

# Spring Boot Login Info
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

# App Config
spring.application.name=My South Church Backend

# Tells Spring Security: "Trust tokens signed by Google/Firebase"
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/my-south-church

# The "Root" group that everyone must be in
google.groups.root-group=${GOOGLE_ROOT_GROUP_EMAIL}

# Tell Spring to look at the "X-Forwarded-Proto" header
server.forward-headers-strategy=framework

# Trust the load balancer's IP
server.tomcat.remoteip.internal-proxies=.*

# Database Connection URL
spring.datasource.url=${DB_URL}

# Database Credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Settings
# "update" automatically creates tables if they don't exist (Good for Dev/Test)
# Use "validate" or "none" for strict Production
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (Optional, helpful for debugging)
spring.jpa.show-sql=true
